# Main bot configuration file

# Settings used for active development
[development]
debug = true

# Settings for bot usage
[parameters]
displayGraph = false
SentimentScoreWeighted = true
SentimentScoreThreshold = 0
WebScraperMaxElements = 20