# Main bot configuration file

# Settings used for active development
[development]
debug = false

# Settings for bot usage
[parameters]
displayGraph = true
SentimentScoreWeighted = true
SentimentScoreThreshold = 20
WebScraperMaxElements = 20